theme: minima
title: Your awesome title
author: Mian Jawad Ahmad
email: a.jawad321@gmail.com
description: > # this means to ignore newlines until "baseurl:"
not now

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # React Native
